theme: jekyll-theme-minimal
title: CV Jana Rolki
description: Nazywam się Jan Rolka i jestem studentem pierwszego roku na kierunku Informatyka i Systemy Inteligentne na Akademii Górniczo-Hutniczej w Krakowie
